---
# Homepage widgets
# Documentation: https://gethomepage.dev/configs/widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
